- hosts: aws_ec2
  become: yes
  tasks:
    - name: Update apt cache and install Nginx
      yum:
        name: nginx
        state: latest
        update_cache: yes

    - name: Start nginx
      service:
        name: nginx
        state: started